#!/usr/bin/env python3

import logging
import time
import os

from subcontractor.daemon import Daemon
from subcontractor.contractor import Contractor
from subcontractor.dhcpd import DHCPd
from subcontractor.dynamic_pool import DynamicPool
from subcontractor.static_pool import StaticPool

# in seconds
STATIC_LEASE_TIME = 1800
DYNAMIC_LEASE_TIME = 300


class Main( Daemon ):  # TODO: cache to local cache file
  default_config_file = '/etc/subcontractor.conf'

  def __init__( self, *args, **kwargs ):
    super().__init__( 'subcontractor', *args, **kwargs )
    self.cache_file = None
    self.contractor = None
    self.site = None
    self.cont = True
    self.handler = None
    self.dhcpd = None
    self.static_pool = StaticPool( STATIC_LEASE_TIME )

  def config( self, config ):
    self.cache_file = config.get( 'dhcpd', 'cache_file' )
    self.site = config.get( 'subcontractor', 'site' )
    host = config.get( 'contractor', 'host' )
    root_path = config.get( 'contractor', 'root_path' )
    proxy = config.get( 'contractor', 'proxy', fallback=None )
    if not proxy:
      proxy = None

    self.contractor = Contractor( self.site, host=host, root_path=root_path, proxy=proxy )
    item = self.contractor.getSite()
    if item is None:
      raise ValueError( 'site "{0}" does not exist'.format( self.site ) )

    logging.info( 'working with site "{0}"({1})'.format( item[ 'description' ], item[ 'name' ] ) )

    self.poll_interval = config.getint( 'dhcpd', 'poll_interval' )
    self.listen_interface = config.get( 'dhcpd', 'listen_interface' )
    self.listen_address = config.get( 'dhcpd', 'listen_address' )
    self.tftp_server = config.get( 'dhcpd', 'tftp_server' )

  def main( self ):
    logging.info( 'starting dhcp server...' )
    self.dhcpd = DHCPd( self.listen_interface, self.listen_address, self.tftp_server )
    if os.path.isfile( self.cache_file ):
      self.dhcpd.load_cache( self.cache_file )
    self.dhcpd.add_pool( self.static_pool, '__static__' )  # static pools need to be added first so they are searched first
    self.dhcpd.start()
    logging.info( 'running...' )
    while self.cont:
      try:
        dynamic_pool_list = self.contractor.getDHCPdDynamidPools()
        pool_names = [ '__static__' ]

        for dynamic_pool in dynamic_pool_list:
          name = dynamic_pool[ 'name' ]
          pool_names.append( name )
          if name not in self.dhcpd.pool_names:
            pool = DynamicPool( DYNAMIC_LEASE_TIME )
            pool.update_paramaters( dynamic_pool[ 'gateway' ], dynamic_pool[ 'netmask' ], dynamic_pool[ 'dns_server' ], dynamic_pool[ 'domain_name' ], dynamic_pool[ 'address_map' ] )
            self.dhcpd.add_pool( pool, name )

          else:
            self.dhcpd.get_pool( name ).update_paramaters( dynamic_pool[ 'gateway' ], dynamic_pool[ 'netmask' ], dynamic_pool[ 'dns_server' ], dynamic_pool[ 'domain_name' ], dynamic_pool[ 'address_map' ] )

        self.static_pool.update( self.contractor.getDHCPdStaticPools() )

        for name in set( self.dhcpd.pool_names ) - set( pool_names ):
          self.dhcpd.del_pool( name )

        self.dhcpd.cleanup()

        logging.info( 'summary: {0}'.format( self.dhcpd.summary() ) )
        self.dhcpd.save_cache( self.cache_file )

        logging.debug( 'sleeping for "{0}"...'.format( self.poll_interval ) )
        for _ in range( 0, self.poll_interval ):
          if not self.cont:
            break
          time.sleep( 1 )  # using time.sleep instead of a event.wait( timeout=? ) to avoid time warping problems

      except Exception:
        logging.exception( 'Exception occured during main loop' )
        self.dhcpd.stop()
        self.cont = False

    self.dhcpd.save_cache( self.cache_file )
    logging.info( 'waiting for dhcp server...' )
    self.dhcpd.join()
    logging.info( 'done.' )

  def stop( self ):
    logging.info( 'got stop signal' )
    self.cont = False
    if self.dhcpd is not None:
      self.dhcpd.stop()


if __name__ == '__main__':
  Main().run()
