#!/usr/bin/env python3

import sys
import logging
import time

sys.path.insert( 1, '..')

from subcontractor.daemon import Daemon
from subcontractor.contractor import Contractor
from subcontractor.dhcpd import DHCPd
from subcontractor.dynamic_pool import DynamicPool


class Main( Daemon ):
  default_config_file = '/etc/subcontractor.conf'

  def __init__( self, *args, **kwargs ):
    super().__init__( 'subcontractor', *args, **kwargs )
    self.contractor = None
    self.site = None
    self.cont = True
    self.handler = None
    self.dhcpd = None
    self.dynamic_pool_map = {}
    self.static_pool_map = {}

  def config( self, config ):
    self.site = config.get( 'subcontractor', 'site' )
    host = config.get( 'contractor', 'host' )
    root_path = config.get( 'contractor', 'root_path' )
    port = config.get( 'contractor', 'port' )
    proxy = config.get( 'contractor', 'proxy' )
    if not proxy:
      proxy = None

    self.contractor = Contractor( self.site, host=host, root_path=root_path, port=port, proxy=proxy )
    item = self.contractor.getSite()
    if item is None:
      raise ValueError( 'site "{0}" does not exist'.format( self.site ) )

    logging.info( 'working with site "{0}"({1})'.format( item[ 'description' ], item[ 'name' ] ) )

    self.poll_interval = config.getint( 'dhcpd', 'poll_interval' )
    self.listen_interface = config.get( 'dhcpd', 'listen_interface' )
    self.listen_address = config.get( 'dhcpd', 'listen_address' )
    self.tftp_server = config.get( 'dhcpd', 'tftp_server' )


  def main( self ):
    logging.debug( 'starting dhcp server...' )
    self.dhcpd = DHCPd( self.listen_interface, self.listen_address, self.tftp_server )
    self.dhcpd.start()
    logging.debug( 'running...' )
    while self.cont:
      dynamic_pool_list = self.contractor.getDHCPdDynamidPools()
      static_map = self.contractor.getDHCPdStaticPools()
      print( '--- dynamic pools ---')
      print( dynamic_pool_list )
      print( '--- static mac entries ---' )
      print( static_map )
      for site in static_map:
        try:
          pool = self.static_pool_map[ site ]
        except KeyError:
          logging.info( 'Creating static pool for site "{0}"'.format( site ) )
          pool = DynamicPool()
          self.static_pool_map[ site ] = pool

        pool.update( static_map[ site ] )

      for site in set( self.static_pool_map.keys() ) - set( static_map.keys() ):
        logging.info( 'Removing static pool for site "{0}"'.format( site ) )
        del self.static_pool_map[ site ]

      logging.debug( 'sleeping for "{0}"...'.format( self.poll_interval ) )
      for _ in range( 0, self.poll_interval ):
        if not self.cont:
          break
        time.sleep( 1 )  # using time.sleep instead of a event.wait( timeout=? ) to avoid time warping problems

    logging.debug( 'waiting for dhcp server...' )
    self.dhcpd.wait()
    logging.debug( 'done.' )

  def stop( self ):
    self.cont = False
    if self.dhcpd is not None:
      self.dhcpd.stop()

if __name__ == '__main__':
  Main().run()
